### ISSUE TITLE
Stopped working after Firefox update

### ISSUE THREAD

**Issue by seso101** [wildskyf/personal-blocklist#24] opened 2018-09-21 22:43 UTC
Hi, Firefox updated itself to version 62.0 earlier on and unfortunately the personal blocklist function has disappeared from my google searches.

**Comment by bigdocmcd** [comment] 2018-09-22 02:03
personal blocklist (not by google) 2.9.0 function disappeared on firefox 62.0.2 or 62.0

**Comment by wildskyf** [comment] 2018-09-23 14:40
thanks for your reporting!
I will fix the bug soon.

It might be fixed before 10/11 because I am busy before that date...

**Comment by taxen** [comment] 2018-09-27 03:55
I stick to version 56.0.2 and it also stops working. I will look forward to see some update. Thank you!

**Comment by bigdocmcd** [comment] 2018-09-29 21:46
Thanks, my blocklist is now working. 9/29

**Comment by bigdocmcd** [comment] 2018-09-29 21:54
It now appears to be working again.  Guess you must have fixed it.

**Comment by MarjaE2** [comment] 2018-09-30 00:01
Also recently failed in Waterfox 56. Not yet working again.

**Comment by taxen** [comment] 2018-09-30 00:59
Guess what? Mine also started to work!
Since no commit has been made, I think this is due to Google's end.

Anyway, thank you! @wildskyf

**Comment by dixonge** [comment] 2018-10-01 12:27
STILL NOT WORKING

Firefox 62
Kubuntu 18.04

I uninstalled, restarted FF, reinstalled, restarted FF - still get no option on Google search results to block any sites.

**Comment by MarjaE2** [comment] 2018-10-01 22:53
Should this show in the inspector? Is there anything I can do to help figure out why it's not working for me?

**Comment by bigdocmcd** [comment] 2018-10-02 01:09
Funny thing - on firefox now I have 2 options for each entry, for example
Block dictionary.com
Block dictionary.com

From no option, to 1 option to 2 options. Should have stopped when it was right.

**Comment by wildskyf** [comment] 2018-10-02 04:46
Hi all, thank you guys for reporting problem here.

I will check the problem, try to reproduce, and see whether it could be solved by add-on itself or it is Google's problem. I guess it is caused by Google's new HTML struct, and problem might or might not happened by people. (Google's personalize you know.)

Anyway, I will check it in this Sunday, and if you are willing to, please leave these information here so that I could debug easilier:

- OS version (e.g., Windows 10, Kubuntu 18.04, ... etc)
- Firefox version (e.g, Firefox 62, Waterfox 56.2.3, ... etc)
- Personal Blocklist version (e.g, 2.8.0, 2.9.0, ... etc)

Thank you all again! I am happy that this add-on is used by so many people. :)

**Comment by MarjaE2** [comment] 2018-10-02 05:08
Thank you!

MacOS 10.12.6
Waterfox 56.2.3
Personal Blocklist 2.9.0
Not working

**Comment by ysu2** [comment] 2018-10-02 09:58
It stopped working for me, too.   I guess google must have changed something, as I'm on v61.0.2 of  firefox.

**Comment by ysu2** [comment] 2018-10-04 06:28
For me it does not depend on the entered text.  Normal search, normal English text; nothing.

**Comment by wildskyf** [comment] 2018-10-07 08:13
@seso101 @ysu2 @taxen  @MarjaE2 @bigdocmcd  @dixonge I just upload a new version to AMO. (v2.10.0)

Please try it and report to me whether your blocklinks come back! Thanks for your patience!

**Comment by taxen** [comment] 2018-10-07 11:30
@wildskyf To me, the situation after updating to 2.11.1 is the same as before. Simple "メレル" search does not show links to block. Other searches do.

**Comment by wildskyf** [comment] 2018-10-07 11:38
@taxen, thanks for your report. If you doesn't find it back, it means the bug is still not solved for someone else. I want to debug in your situation. Here are the steps:

1) search "メレル"
2) press `ctrl/command + s` to save page as html file
3) archived the html file and folder to `zip`
4) send the zip file to my email: <poppin.wildsky+pb@gmail.com>

Can you do me a favor?

**Comment by dixonge** [comment] 2018-10-07 12:32
Odd - ran updates on FF extension - blocklist updated to 2.11.1 !

Also, it works now. Thank you!

**Comment by MarjaE2** [comment] 2018-10-07 15:08
Here too, thanks!

**Comment by ysu2** [comment] 2018-10-07 21:52
Yep, working again, many thanks!

**Comment by GrahmB03** [comment] 2018-10-08 12:51
Updated to 2.11.1 from 2.09 but still having poblems.
In Firefox it either misses blocked sites or blocks completely all search results just leaving the few google sponsored images/ads on top line. 
So frustrating.

**Comment by wildskyf** [comment] 2018-10-08 13:18
@GrahmB03 Could you please show me your blocklist?
Because I changed the block pattern before, now the search result would be blocked as long as its url contains any string in your list.

e.g., if you block `.`, you will find all results removed by add-on.

**Comment by wildskyf** [comment] 2018-11-06 14:40
Thank you all, I am going to close this issue.
If you still got problems about this issue, feel free to reopen it.

**Closed by wildskyf** 2018-11-06 14:40 UTC
Labels: bug
